// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaRnHC7CvB6P7v7NfPqXm1pp0fPGdlffM',
    appId: '1:291215112396:web:9a27705acd2ae8d7a1aa69',
    messagingSenderId: '291215112396',
    projectId: 'new-chat-app-4579d',
    authDomain: 'new-chat-app-4579d.firebaseapp.com',
    storageBucket: 'new-chat-app-4579d.appspot.com',
    measurementId: 'G-5VW7X7BG6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqMtdrpc_RD-ItYolLzhIBj4K2Fp3lyGc',
    appId: '1:291215112396:android:49d32b53e32f7aa1a1aa69',
    messagingSenderId: '291215112396',
    projectId: 'new-chat-app-4579d',
    storageBucket: 'new-chat-app-4579d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADmKI1mgQhk4JC1PbZkyOXMYNbMzPPx2o',
    appId: '1:291215112396:ios:6eddfb593e0e71cba1aa69',
    messagingSenderId: '291215112396',
    projectId: 'new-chat-app-4579d',
    storageBucket: 'new-chat-app-4579d.appspot.com',
    iosBundleId: 'com.example.newVersionOfChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADmKI1mgQhk4JC1PbZkyOXMYNbMzPPx2o',
    appId: '1:291215112396:ios:210a7944402627aaa1aa69',
    messagingSenderId: '291215112396',
    projectId: 'new-chat-app-4579d',
    storageBucket: 'new-chat-app-4579d.appspot.com',
    iosBundleId: 'com.example.newVersionOfChatApp.RunnerTests',
  );
}
